#pragma once

// clang-format off

#define ENUM_DEVICE_MODE(ENUM) \
  ENUM(OFF, 0x00), ENUM(CHARGER_ON, 0x01), ENUM(INVERTER_ON, 0x02), ENUM(DEVICE_ON, 0x03), ENUM(DEVICE_OFF, 0x04), \
  ENUM(ECO, 0x05), ENUM(HIBERNATE, 0xFD)

#define ENUM_DEVICE_STATE(ENUM) \
  ENUM(OFF, 0x00), ENUM(LOW_POWER, 0x01), ENUM(FAULT, 0x02), ENUM(BULK, 0x03), ENUM(ABSORPTION, 0x04), \
  ENUM(FLOAT, 0x05), ENUM(STORAGE, 0x06), ENUM(EQUALIZE_MANUAL, 0x07), ENUM(PASSTHRU, 0x08), \
  ENUM(INVERTING, 0x09), ENUM(ASSISTING, 0x0A), ENUM(POWER_SUPPLY, 0x0B), ENUM(SUSTAIN, 0xF4), \
  ENUM(STARTING_UP, 0xF5), ENUM(REPEATED_ABSORPTION, 0xF6), ENUM(AUTO_EQUALIZE, 0xF7), \
  ENUM(BATTERY_SAFE, 0xF8), ENUM(EXTERNAL_CONTROL, 0xFC), ENUM(UNKNOWN, 0xFF)

// clang-format on