#pragma once
#include "ve_reg_macro.h"
// clang-format off

#define REGISTERS_COMMON(MACRO) \
  MACRO(BITMASK, 0x0090, BLE_MODE, READ_WRITE, uint8_t) \
  MACRO(STRING, 0x010A, SERIAL_NUMBER, READ_ONLY) \
  MACRO(STRING, 0x010B, MODEL_NAME, READ_ONLY) \
  MACRO(ENUM, 0x0200, DEVICE_MODE, READ_WRITE) \
  MACRO(ENUM, 0x0201, DEVICE_STATE, READ_ONLY) \
  MACRO(BITMASK_S, 0x0205, DEVICE_OFF_REASON, READ_ONLY, uint8_t, DEVICE_OFF_REASON_2) \
  MACRO(BITMASK, 0x0207, DEVICE_OFF_REASON_2, READ_ONLY, uint32_t) \
  MACRO(BITMASK, 0x031C, WARNING_REASON, READ_ONLY, uint16_t) \
  MACRO(BITMASK_S, 0x031E, ALARM_REASON, READ_ONLY, uint16_t, WARNING_REASON) \
  MACRO(BOOLEAN, 0x034E, RELAY_CONTROL, READ_WRITE) \
  IF(DEF_BMV)(MACRO(NUMERIC, 0x0FFE, TTG, READ_ONLY, uint16_t, minute, S_1, S_1)) \
  IF(DEF_BMV)(MACRO(NUMERIC, 0x0FFF, SOC, READ_ONLY, uint16_t, SOC_PERCENTAGE, S_0_01, S_0_1)) \
  IF(DEF_INV)(MACRO(NUMERIC, 0x2200, AC_OUT_VOLTAGE, READ_ONLY, int16_t, V, S_0_01, S_0_01)) \
  IF(DEF_INV)(MACRO(NUMERIC, 0x2201, AC_OUT_CURRENT, READ_ONLY, int16_t, A, S_0_1, S_0_1)) \
  IF(DEF_INV)(MACRO(NUMERIC, 0x2205, AC_OUT_APPARENT_POWER, READ_ONLY, int32_t, VA, S_1, S_1)) \
  MACRO(NUMERIC, 0xED8D, DC_CHANNEL1_VOLTAGE, READ_ONLY, int16_t, V, S_0_01, S_0_001) \
  IF(DEF_BMV)(MACRO(NUMERIC, 0xED8E, DC_CHANNEL1_POWER, READ_ONLY, int16_t, W, S_1, S_1)) \
  MACRO(NUMERIC, 0xED8F, DC_CHANNEL1_CURRENT, READ_ONLY, int16_t, A, S_0_1, S_0_001) \
  IF(DEF_MPPT)(MACRO(BOOLEAN, 0xEDA8, LOAD_OUTPUT_STATE, READ_ONLY)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDAD, LOAD_CURRENT, READ_ONLY, uint16_t, A, S_0_1, S_0_001)) \
  IF(DEF_MPPT)(MACRO(ENUM, 0xEDB3, MPPT_TRACKER_MODE, READ_ONLY)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDB8, PANEL_MAXIMUM_VOLTAGE, READ_ONLY, uint16_t, V, S_0_01, S_0_01)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDBB, PANEL_VOLTAGE, READ_ONLY, uint16_t, V, S_0_01, S_0_001)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDBC, PANEL_POWER, READ_ONLY, uint32_t, W, S_0_01, S_1)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDBD, PANEL_CURRENT, READ_ONLY, uint16_t, A, S_0_1, S_0_1)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDD0, MAXIMUM_POWER_YESTERDAY, READ_ONLY, uint16_t, W, S_1, S_1)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDD1, YIELD_YESTERDAY, READ_ONLY, uint16_t, kWh, S_0_01, S_0_01)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDD2, MAXIMUM_POWER_TODAY, READ_ONLY, uint16_t, W, S_1, S_1)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDD3, YIELD_TODAY, READ_ONLY, uint16_t, kWh, S_0_01, S_0_01)) \
  IF(DEF_CHG)(MACRO(ENUM, 0xEDDA, CHR_ERROR_CODE, READ_ONLY)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDDC, USER_YIELD, READ_ONLY, uint32_t, kWh, S_0_01, S_0_01)) \
  IF(DEF_MPPT)(MACRO(NUMERIC, 0xEDDD, SYSTEM_YIELD, READ_ONLY, uint32_t, kWh, S_0_01, S_0_01)) \
  IF(DEF_BMV)(MACRO(NUMERIC, 0xEDEC, BAT_TEMPERATURE, READ_ONLY, uint16_t, CELSIUS, S_0_01, S_1)) /*TODO:HEX register carries 0.01K*/ \
  IF(DEF_BMV71)(MACRO(NUMERIC, 0xEEB8, DC_MONITOR_MODE, READ_ONLY, int16_t, NONE, S_1, S_1)) /*might be R/W and it's a signed ENUM*/ \
  IF(DEF_BMV)(MACRO(BOOLEAN, 0xEEFC, ALARM_BUZZER, READ_WRITE))

// clang-format on