#pragma once

// clang-format off

#define REGISTERS_COMMON(MACRO) \
  MACRO##_BITMASK(0x0090, BLE_MODE, READ_WRITE, uint8_t) \
  MACRO##_ENUM(0x0200, DEVICE_MODE, READ_WRITE) \
  MACRO##_ENUM(0x0201, DEVICE_STATE, READ_ONLY) \
  MACRO##_BITMASK_S(0x0205, DEVICE_OFF_REASON, READ_ONLY, uint8_t, DEVICE_OFF_REASON_2) \
  MACRO##_BITMASK(0x0207, DEVICE_OFF_REASON_2, READ_ONLY, uint32_t) \
  MACRO##_BITMASK(0x031C, WARNING_REASON, READ_ONLY, uint16_t) \
  MACRO##_BITMASK_S(0x031E, ALARM_REASON, READ_ONLY, uint16_t, WARNING_REASON) \
  MACRO##_NUMERIC(0x2201, AC_OUT_CURRENT, READ_ONLY, int16_t, D_1, A) \
  MACRO##_ENUM(0xEDDA, CHR_ERROR_CODE, READ_ONLY)

// clang-format on