uart:
  - id: uart_0
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 19200
    rx_buffer_size: 256

m3_antbms:
  - id: antbms_0
    uart_id: uart_0
    object_id_prefix: antbms_0

binary_sensor:
  - platform: m3_antbms
    antbms_id: antbms_0
    link_connected:
      name: UART link

sensor:
  - platform: m3_antbms
    antbms_id: antbms_0
    battery_voltage:
      name: Battery voltage
    battery_current:
      name: Battery current
    battery_power:
      name: Battery power
    battery_energy_in:
      name: Battery energy in
    battery_energy_out:
      name: Battery energy out
    soc:
      name: Soc
    capacity_remaining:
      name: Battery charge
    cell_voltage:
      name: Cell
      count: 16
    cell_high_voltage:
      name: Cell high voltage
    cell_low_voltage:
      name: Cell low voltage
    temperature:
      name: Temperature
      count: 6
    memory_free:
      name: Free memory

text_sensor:
  - platform: m3_antbms
    antbms_id: antbms_0
    charge_mos_status:
      name: Charge MOS status
    discharge_mos_status:
      name: Discharge MOS status
    balance_status:
      name: Balance status
